"""empty message

Revision ID: 009b6747a2ae
Revises: 01c7cd46f303
Create Date: 2020-03-08 05:30:08.736653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '009b6747a2ae'
down_revision = '01c7cd46f303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teamsemp')
    op.add_column('employees', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'team_id')
    op.create_table('teamsemp',
    sa.Column('tid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('eid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['eid'], [u'employees.id'], name=u'teamsemp_ibfk_1'),
    sa.ForeignKeyConstraint(['tid'], [u'teams.id'], name=u'teamsemp_ibfk_2'),
    sa.PrimaryKeyConstraint('tid', 'eid'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
