"""empty message

Revision ID: 04c5f3b0a4ac
Revises: 44c0c35de528
Create Date: 2020-03-30 11:17:49.427663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c5f3b0a4ac'
down_revision = '44c0c35de528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('pid', table_name='empprojects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('pid', 'empprojects', ['pid'], unique=True)
    # ### end Alembic commands ###
