"""empty message

Revision ID: 09a405cc7dd0
Revises: 542636a414e7
Create Date: 2020-03-30 11:22:49.749623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09a405cc7dd0'
down_revision = '542636a414e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empprojects',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('eid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['eid'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['pid'], ['projects.pid'], ),
    sa.PrimaryKeyConstraint('pid', 'eid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empprojects')
    # ### end Alembic commands ###
