"""empty message

Revision ID: 1aff105de5a3
Revises: 1efc4da85aa0
Create Date: 2020-03-08 04:38:58.785743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1aff105de5a3'
down_revision = '1efc4da85aa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teamsemp',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('eid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['eid'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['tid'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('tid', 'eid')
    )
    op.drop_constraint(u'employees_ibfk_2', 'employees', type_='foreignkey')
    op.drop_column(u'employees', 'team_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'employees', sa.Column('team_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'employees_ibfk_2', 'employees', 'teams', ['team_id'], ['id'])
    op.drop_table('teamsemp')
    # ### end Alembic commands ###
