"""empty message

Revision ID: 1efc4da85aa0
Revises: 5c05eeb2ba20
Create Date: 2020-03-06 21:21:10.819403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1efc4da85aa0'
down_revision = '5c05eeb2ba20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('projectname', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('assignprojects',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['projects.pid'], ),
    sa.ForeignKeyConstraint(['tid'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('pid', 'tid')
    )
    op.alter_column(u'assigntasks', 'end_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column(u'assigntasks', 'start_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.add_column(u'employees', sa.Column('is_lead', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'employees', 'is_lead')
    op.alter_column(u'assigntasks', 'start_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column(u'assigntasks', 'end_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_table('assignprojects')
    op.drop_table('projects')
    # ### end Alembic commands ###
