"""empty message

Revision ID: 28aa17833039
Revises: 073c54e75c69
Create Date: 2020-03-19 22:02:02.885789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28aa17833039'
down_revision = '073c54e75c69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignprojects')
    op.add_column('projects', sa.Column('closed', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('tid', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'projects', 'teams', ['tid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'tid')
    op.drop_column('projects', 'start_time')
    op.drop_column('projects', 'closed')
    op.create_table('assignprojects',
    sa.Column('pid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('start_time', mysql.DATETIME(), nullable=True),
    sa.Column('closed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pid'], [u'projects.pid'], name=u'assignprojects_ibfk_1'),
    sa.ForeignKeyConstraint(['tid'], [u'teams.id'], name=u'assignprojects_ibfk_2'),
    sa.PrimaryKeyConstraint('pid', 'tid'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
