"""empty message

Revision ID: 2cd7083c4ceb
Revises: 28aa17833039
Create Date: 2020-03-19 22:26:14.449107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2cd7083c4ceb'
down_revision = '28aa17833039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assigntasks')
    op.add_column('tasks', sa.Column('employeeid', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('iscompleted', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('priority', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'employees', ['employeeid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'start_time')
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'iscompleted')
    op.drop_column('tasks', 'end_time')
    op.drop_column('tasks', 'employeeid')
    op.create_table('assigntasks',
    sa.Column('tid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('employeeid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('end_time', mysql.DATETIME(), nullable=True),
    sa.Column('iscompleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('priority', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('start_time', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['employeeid'], [u'employees.id'], name=u'assigntasks_ibfk_1'),
    sa.ForeignKeyConstraint(['tid'], [u'tasks.tid'], name=u'assigntasks_ibfk_2'),
    sa.PrimaryKeyConstraint('tid', 'employeeid'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
