"""empty message

Revision ID: 44c0c35de528
Revises: 2cd7083c4ceb
Create Date: 2020-03-30 11:17:27.691802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c0c35de528'
down_revision = '2cd7083c4ceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'empprojects', ['pid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'empprojects', type_='unique')
    # ### end Alembic commands ###
