"""empty message

Revision ID: 492e409c2194
Revises: c4ac7687d204
Create Date: 2020-03-06 09:58:32.993167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492e409c2194'
down_revision = 'c4ac7687d204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('tid')
    )
    op.create_table('assigntasks',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('employeeid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employeeid'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['tid'], ['tasks.tid'], ),
    sa.PrimaryKeyConstraint('tid', 'employeeid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assigntasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
