"""empty message

Revision ID: 542636a414e7
Revises: 04c5f3b0a4ac
Create Date: 2020-03-30 11:20:06.248298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542636a414e7'
down_revision = '04c5f3b0a4ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('pid', table_name='empprojects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('pid', 'empprojects', ['pid'], unique=True)
    # ### end Alembic commands ###
