"""empty message

Revision ID: 5c05eeb2ba20
Revises: 492e409c2194
Create Date: 2020-03-06 10:25:53.044381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c05eeb2ba20'
down_revision = '492e409c2194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assigntasks', sa.Column('end_time', sa.DateTime(), nullable=False))
    op.add_column('assigntasks', sa.Column('iscompleted', sa.Boolean(), nullable=True))
    op.add_column('assigntasks', sa.Column('priority', sa.Integer(), nullable=False))
    op.add_column('assigntasks', sa.Column('start_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assigntasks', 'start_time')
    op.drop_column('assigntasks', 'priority')
    op.drop_column('assigntasks', 'iscompleted')
    op.drop_column('assigntasks', 'end_time')
    # ### end Alembic commands ###
