"""empty message

Revision ID: c3363f9a3cf4
Revises: 009b6747a2ae
Create Date: 2020-03-08 09:20:06.771664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3363f9a3cf4'
down_revision = '009b6747a2ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empprojects',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('eid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['eid'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['pid'], ['projects.pid'], ),
    sa.PrimaryKeyConstraint('eid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empprojects')
    # ### end Alembic commands ###
