"""empty message

Revision ID: c4cbb6567a4d
Revises: ef7f79c78ad6
Create Date: 2020-04-28 14:11:20.595426

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4cbb6567a4d'
down_revision = 'ef7f79c78ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tgroup', sa.Column('gname', sa.String(length=256), nullable=False))
    op.drop_column('tgroup', 'group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tgroup', sa.Column('group', mysql.VARCHAR(length=256), nullable=False))
    op.drop_column('tgroup', 'gname')
    # ### end Alembic commands ###
