"""empty message

Revision ID: e38b518b3c66
Revises: 09a405cc7dd0
Create Date: 2020-04-28 12:14:13.136461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e38b518b3c66'
down_revision = '09a405cc7dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tgroup',
    sa.Column('gid', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('gid')
    )
    op.add_column(u'tasks', sa.Column('groupid', sa.Integer(), nullable=False))
    op.alter_column(u'tasks', 'task',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.create_foreign_key(None, 'tasks', 'tgroup', ['groupid'], ['gid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.alter_column(u'tasks', 'task',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.drop_column(u'tasks', 'groupid')
    op.drop_table('tgroup')
    # ### end Alembic commands ###
